### ISSUE TITLE
Future implementation?

### ISSUE THREAD

**Issue by EnricoBara** [AndrewParkes/BlockAllSteamInvites#3]
Hi again, hope to don't bother you.

I found a good way, thanks to the "suggestions" of your extension, that can helps remove other scammers. Actually, with your extension, I have to manually ignore 20-30 users a day.

My implementation target is for Dota 2, but I think it is bossible to add a textbox where anyone write his game/games.

The only one thing I'm missing for totally erase the scammer, is adding the time playied for a game, as you know, scammers has <200 hours playied (except from stolen accounts) so I'm asking you if u can help me to add the var that excludes the <200 hrs playied.

This is the code, I won't share it, is for personal use only

 https://greasyfork.org/en/scripts/11272-autoblocks-all-steam-invites-eb-with-dota

Best regards

**Comment by AndrewParkes** [comment]
I have block by number of hours in my future additions but havent had time to add all those additions but will in the future.

With regards to blocking depending on what games the user has: If steam only had one or two "trading" games it would be fine cause you would check just for those games. The problem is that there are a lot more than that. People also can have items for games they actually dont own -Like most secret traders that dont trade on their main account-
Allowing users to block on user input of what games they think the user has makes it a little cumbersome to have. You can use my block user by level and take the text box and implement it yourself.

Having something that is directed to a specific game or games doesnt help make the script accessible. For your implementation only dota 2 players are then not blocked and any account without it is blocked. Thus I cant put into the live script. Keep it in your personal script and if you want help improving it just ask but its not something that will be added.

**Comment by EnricoBara** [comment]
Yeah infact for a public version, a single players should choose the game
he plays. I'll wait your block by hours for completing this script. Best
regards

 | enrico baravelli

2015-07-28 8:51 GMT+02:00 AndrewParkes notifications@github.com:

**Comment by AndrewParkes** [comment]
Even if there is a text box for a user to enter a game, something as simple as a spelling error will block all the user's.

**Comment by EnricoBara** [comment]
I know I know. A simple guide to _copy the game name_ isn't enought

 | enrico baravelli

2015-07-28 11:35 GMT+02:00 AndrewParkes notifications@github.com:
